server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/v2/accounts/ {
    proxy_pass http://account-core-service:8081/api/v2/accounts/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location = /api/v2/accounts {
    proxy_pass http://account-core-service:8081/api/v2/accounts;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location /api/v2/account-subtypes {
    proxy_pass http://account-core-service:8081/api/v2/account-subtypes;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location /api/v2/calendar/ {
    proxy_pass http://account-core-service:8081/api/v2/calendar/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location /api/v2/customers/ {
    proxy_pass http://party-service:8083/api/v2/customers/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location = /api/v2/customers {
    proxy_pass http://party-service:8083/api/v2/customers;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location /api/v2/customer-subtypes {
    proxy_pass http://party-service:8083/api/v2/customer-subtypes;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location /api/v2/branches {
    proxy_pass http://party-service:8083/api/v2/branches;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Origin "";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
