sonar.projectKey=Banco-BanQuito_banquito-frontend-web-operador
sonar.organization=banco-banquito
sonar.projectName=BanQuito Frontend Web Operador
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*
